# https://docs.docker.com/compose/compose-file/
# https://docs.docker.com/compose/compose-file/05-services/

services:
  marp:
    image: marpteam/marp-cli:v4.2.0
    volumes:
      - ./docs/:/docs
    working_dir: /docs
    ports:
      - 37717:37717
    command:
      - "--config-file=./marprc.yml"
      - "--debug"
    profiles:
      - slides

